namespace FRS.Common.Enums
{
    public enum LoggingActions
    {
        Login = 1,
        Logout = 2,
        ChangePassword,
        ResetPassword,
        CopyEvent,
        CreateEvent,
        EditBasicData,
        ImportAttendees,
        DeleteAssignedAttendee,
        AssignAttendee = 10,
        EditAgenda,
        CostModification,
        ImportCosts,
        CopyCosts,
        ActionExecution,
        ChangeDeadline,
        EditAttendee,
        AssignToEvent,
        SetAttendeeToInactive,
        CreateUser = 20,
        EditUserData,
        ChangeUserPassword,
        LockUser,
        UnlockUser,
        RoleModification,
        RoleToUserAssignment,
        DataroleToUserAssignment,
        DataRoleModification,
        ImportCompanies,
        SetCompanyToActiveInactive = 30,
        EditCompany,
        ImportDepartments,
        SetDepartmentToActiveInactive,
        EditDepartment,
        ImportCostCenters,
        SetCostCenterToActiveInactive,
        EditCostCenter,
        EditWorkflowStep,
        DeleteWorkflowStep,
        CreateWorkflow = 40,
        EditWorkflow,
        ImportCustomization,
        SetEventTypeToActiveInactive,
        VIPLoungeCreation,
        VIPLoungeModification,
        VIPLoungeReleasing,
        VIPLoungeSetDateAsNotAvailable,
        UpdateDocumentForEvent,
        DeleteDocumentForEvent,
        VIPLoungeSetToActiveInactive = 50,
        EditEMailTemplate,
        EventVersionUpdate,
        EditBookingSuggestionMapping,
        EditWorkflowStepPermission,
        DeleteWorkflowStepPermission,
        AddSubstitute,
        DeactivateSubstitute,
        LoginAsSubstitute,
        WageTypeMappingsModification,
        MappingEventTypesModification = 60,
        WageTypeTaxationEditTransferred = 61,
        SocialSecurityEditTransferred = 62,
        CostWasMarkedAsClearingCost = 63,
        CostsWereAllocatedToEvent = 64,
        CostsWereAllocatedToCostCategory = 65,
        AllocationToEventWasReset = 66,
        AllocationToCostCategoryWasReset = 67,
        AllocationWasCommited = 68,
        CostWasMarkedAsIrrelevant = 69,
        FinancialAccountingEditTransferred = 70, // Ingram
        ImportTeams = 71,
        ImportOrderNumbers = 72,
        CreateOrderNumber = 77,
        UpdateOrderNumber = 78,
        CreateCompetitor = 79,
        UpdateCompetitor = 80,
        DeleteCompetitor = 81,
        CreateSeason = 82,
        UpdateSeason = 83,
        DeleteSeason = 84,
        ImportDates = 85,
        CreateTeam = 86,
        UpdateTeam = 87,
        CreateSportToDepartmentConnection = 88,
        UpdateSportToDepartmentConnection = 89,
        CreateSport = 90,
        UpdateSport = 91,
        /// <summary>For adidas</summary>
        CreateRecipientToSportConnection = 92,
        /// <summary>For adidas</summary>
        UpdateRecipientToSportConnection = 93,
        /// <summary>For adidas</summary>
        DeleteRecipientToSportConnection = 94,
        VipLoungeBasicFieldsUpdated = 95,
        UpdateVipLoungePlace = 96,
        VipLoungeCopied = 97,
        EventCancelled = 98,
        EventReservedPlacesNotificationEmailSent = 99,
        CreateVipLoungePlace = 100,
        AssignAttendeeEdited = 101,
        /// <summary>For adidas</summary>
        InitiationStepCompletedEmailsSent = 102,
        /// <summary>For adidas</summary>
        TaxStepCompletedEmailsSent = 103,
        NewAssignAttendee = 104,
        AddPermissionToRole = 105,
        RemovePermissionFromRole = 106,
        UpdatePermissionToRoleAssignment = 107,
        Limit10KEuroEditProcessed = 108,
        Limit35EuroEditProcessed = 109,
        /// <summary>For adidas</summary>
        CreateExpenseAccount = 110,
        /// <summary>For adidas</summary>
        UpdateExpenseAccount = 111,
    }
}
